'use server';
import {revalidatePath} from 'next/cache'; import {redirect} from 'next/navigation'; import {prisma} from '@/lib/db/prisma'; import {requireRole} from '@/lib/auth/queries';
async function teacher(){return requireRole('TEACHER','ADMIN')}
async function ownedLesson(id:string,userId:string){const actor=await prisma.profile.findUnique({where:{id:userId}});const where=actor?.role==='ADMIN'?{id}:{id,teacherId:userId};const l=await prisma.lesson.findFirst({where});if(!l) throw new Error('Không tìm thấy lesson hoặc không có quyền.');return l;}
export async function createLesson(formData:FormData){const u=await teacher();const title=String(formData.get('title')??'').trim();if(!title)throw new Error('Tên bài học là bắt buộc.');const l=await prisma.lesson.create({data:{title,description:String(formData.get('description')??'').trim()||null,teacherId:u.id,versions:{create:{versionNumber:1,status:'DRAFT',source:'MANUAL',createdById:u.id}}}});redirect(`/teacher/lessons/${l.id}`)}
async function getDraft(lessonId:string,userId:string){await ownedLesson(lessonId,userId);let d=await prisma.lessonVersion.findFirst({where:{lessonId,status:'DRAFT'},orderBy:{versionNumber:'desc'}});if(d)return d;const last=await prisma.lessonVersion.findFirst({where:{lessonId},orderBy:{versionNumber:'desc'},include:{cardVersions:true}});const versionNumber=(last?.versionNumber??0)+1;return prisma.$transaction(async tx=>{const nd=await tx.lessonVersion.create({data:{lessonId,versionNumber,status:'DRAFT',source:'MANUAL',createdById:userId}});if(last){for(const c of last.cardVersions) await tx.flashcardVersion.create({data:{flashcardId:c.flashcardId,lessonVersionId:nd.id,frontText:c.frontText,backText:c.backText,exampleSentence:c.exampleSentence,source:c.source}})}return nd;});}
export async function addCard(lessonId:string,formData:FormData){const u=await teacher();const d=await getDraft(lessonId,u.id);const front=String(formData.get('frontText')??'').trim(),back=String(formData.get('backText')??'').trim();if(!front||!back)throw new Error('Mặt trước và mặt sau là bắt buộc.');await prisma.flashcard.create({data:{lessonId,versions:{create:{lessonVersionId:d.id,frontText:front,backText:back,exampleSentence:String(formData.get('exampleSentence')??'').trim()||null,source:'MANUAL'}}}});revalidatePath(`/teacher/lessons/${lessonId}`)}
export async function updateCard(lessonId:string,flashcardId:string,formData:FormData){const u=await teacher();const d=await getDraft(lessonId,u.id);const front=String(formData.get('frontText')??'').trim(),back=String(formData.get('backText')??'').trim();if(!front||!back)throw new Error('Mặt trước và mặt sau là bắt buộc.');await prisma.flashcardVersion.update({where:{flashcardId_lessonVersionId:{flashcardId,lessonVersionId:d.id}},data:{frontText:front,backText:back,exampleSentence:String(formData.get('exampleSentence')??'').trim()||null}});revalidatePath(`/teacher/lessons/${lessonId}`)}
export async function deleteCard(lessonId:string,flashcardId:string){const u=await teacher();const d=await getDraft(lessonId,u.id);await prisma.flashcardVersion.deleteMany({where:{lessonVersionId:d.id,flashcardId}});revalidatePath(`/teacher/lessons/${lessonId}`)}
export async function publishVersion(lessonId:string,versionId:string,formData:FormData){const u=await teacher();await ownedLesson(lessonId,u.id);const v=await prisma.lessonVersion.findFirst({where:{id:versionId,lessonId,status:'DRAFT'}});if(!v)throw new Error('Draft không hợp lệ.');await prisma.$transaction(async tx=>{await tx.lessonVersion.updateMany({where:{lessonId,status:'PUBLISHED'},data:{status:'ARCHIVED'}});await tx.lessonVersion.update({where:{id:v.id},data:{status:'PUBLISHED',publishedAt:new Date(),note:String(formData.get('note')??'').trim()||null}});await tx.lesson.update({where:{id:lessonId},data:{currentPublishedVersionId:v.id}})});revalidatePath(`/teacher/lessons/${lessonId}`);redirect(`/teacher/lessons/${lessonId}/history`)}
export async function rollbackVersion(lessonId:string,targetId:string){const u=await teacher();await ownedLesson(lessonId,u.id);const target=await prisma.lessonVersion.findFirst({where:{id:targetId,lessonId},include:{cardVersions:true}});if(!target)throw new Error('Version không tồn tại.');const latest=await prisma.lessonVersion.findFirst({where:{lessonId},orderBy:{versionNumber:'desc'}});await prisma.$transaction(async tx=>{await tx.lessonVersion.updateMany({where:{lessonId,status:'PUBLISHED'},data:{status:'ARCHIVED'}});const nv=await tx.lessonVersion.create({data:{lessonId,versionNumber:(latest?.versionNumber??0)+1,status:'PUBLISHED',source:target.source,note:`Rollback từ v${target.versionNumber}`,createdById:u.id,publishedAt:new Date()}});for(const c of target.cardVersions) await tx.flashcardVersion.create({data:{flashcardId:c.flashcardId,lessonVersionId:nv.id,frontText:c.frontText,backText:c.backText,exampleSentence:c.exampleSentence,source:c.source}});await tx.lesson.update({where:{id:lessonId},data:{currentPublishedVersionId:nv.id}})});revalidatePath(`/teacher/lessons/${lessonId}/history`)}
